# Generated by Django 4.2.6 on 2023-10-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shortDescrip',
            field=models.TextField(),
        ),
    ]
