# Generated by Django 4.2.6 on 2023-10-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_user_havereaded_alter_user_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
